#!/bin/bash

which ipcalc &>/dev/null || { echo "executable 'ipcalc' not found in PATH" 1>&2; exit 10; }
which uuid &>/dev/null || { echo "executable 'uuid' not found in PATH" 1>&2; exit 10; }

sourceconfig=/etc/sysconfig/ccc
source "$sourceconfig"

test -z "$CCC_NODESDIR" && { echo "missing config parameter CCC_NODESDIR from $sourceconfig" 1>&2; exit 10; }
test -z "$CCC_PXEDIR" && { echo "missing config parameter CCC_PXEDIR from $sourceconfig" 1>&2; exit 10; }
test -z "$CCC_CACHEDIR" && { echo "missing config parameter CCC_CACHEDIR from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_OEMDIR" && { echo "missing config parameter CCC_OEMDIR from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_SERVERKEYFILE" && { echo "missing config parameter CCC_SERVERKEYFILE from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_COREOS_VERSIONS" && { echo "missing config parameter CCC_COREOS_VERSIONS from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_ARPTYPE" && { echo "missing config parameter CCC_ARPTYPE from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_CLOUDINIT_TEMPLATE" && { echo "missing config parameter CCC_CLOUDINIT_TEMPLATE from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_SERVERDOMAIN" && { echo "missing config parameter CCC_SERVERDOMAIN from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_CLUSTERDOMAIN" && { echo "missing config parameter CCC_CLUSTERDOMAIN from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_NODES_GATEWAY" && { echo "missing config parameter CCC_NODES_GATEWAY from $sourceconfig" 1>&2; exit 1; }
test -z "$CCC_NODES_DNS" && { echo "missing config parameter CCC_NODES_DNS from $sourceconfig" 1>&2; exit 1; }

test -z "$CCC_SERVERIP" && { echo "failed to extract CCC_SERVERIP from $CCC_SERVERIPDATA" 1>&2; exit 1; }
test -z "$CCC_SERVERPREFIX" && { echo "failed to extract CCC_SERVERPREFIX from $CCC_SERVERIPDATA" 1>&2; exit 1; }
test -z "$CCC_SERVERSUBNET" && { echo "failed to calculate CCC_SERVERSUBNET from $CCC_SERVERIPDATA" 1>&2; exit 1; }
test -z "$CCC_SERVERNETMASK" && { echo "failed to calculate CCC_SERVERNETMASK from $CCC_SERVERIPDATA" 1>&2; exit 1; }
test -z "$CCC_SERVERBCAST" && { echo "failed to calculate CCC_SERVERBCAST from $CCC_SERVERIPDATA" 1>&2; exit 1; }

USAGE="
usage: ${0##*/} 
usage: ${0##*/} GLOBAL_OPTION
usage: ${0##*/} node_mac_addr [OPTIONS]

The first usage form receives no argument and its equivalent to pass the global option -L, as in the seconds usage form

The second usage form receives a single global-operation option, which can be one of:

	-H			Prints this usage and exits
	-L			This option prints out a summary if each node configuration
        -N                      Performs a global cleanup, removing invalid nodes and hanging nodes data. Also triggers a full 
                                reconfiguration for each remaining valid nodes.
        -R                      Forces reading nodes cluster data and recreate all clusters configuration
				This option is for internal purposes, and normally is not required to be used

The third usage form receives a mac address and an optional set of options, as explained below.

	node_mac_addr  		Mandatory argument. Set to the coreos node MAC. Use the format: xx-xx-xx-xx-xx-xx
				(lowercase letters only)

Options:
	-n 			Specify that this is a new node being registered (so, also specify all non defaults)
	-i ip/prefix  		Specify the node ip address and network prefix
        -h hostname   		Specify the node hostname. Defaults to the mac address prefixed by 'coreos-'
	-c channel:version	Specify the coreos version to use, defaults to stable:current
	-l clustername          Specify the name of the cluster this node belongs to. Default is '-', meaning its isolated.
	-d true|false           Specify if this node will be using a "disk" partition (when true), labeled as "CCCROOT", 
                                for the root filesystem, or the default "tmpfs" in RAM (when false)
	-a true|false		Specify this node requires console autologin
	-s			Show node data. If new data is being set, then show them after new settings.
				If no data is changed then validation is not performed. Add -v in that case.
	-v			Validate current node data even if no new settings are detected
	-V			Same than -v but prints node mac address to stdin on successful validation.
	-f 			Force a server side reconfiguration for this node
				notice that a server side reconfiguration is done anyway if any change is detected on node data
	-F			Same than -f but also forces oem data rebuild
				Notice that a server side reconfiguration is done anyway if any change is detected on node data
	-e			Deregister the node (can't be used with other options)
	-o			Use standard input data as cloud-config.yml configuration for node (instead of the default)
				(can't be used with other options)
	-O			Print the current cloud-config.yml of the node to standard output
				(can't be used with other options)
	-T			Same than -O but translates the referenced variables into values
				(can't be used with other options)
	-r [command [args...]]	Execute a remote command on this node (can't be used with other options), if no command 
 				is given then it will read all commands from STDIN. 
				WARNING: Everything after '-r' will be considered as part of the command.

If no option is provided, then it will exit with 0 if the mac is valid and the node is registered, in any other case 
it will exit with non-zero. If mac is not valid it will print an error message.
	
"

function showdata() {
	nodem=${1:-$node_macaddr}
	test "$CCC_NODESDIR/$nodem" && grep -P '^#' "$CCC_NODESDIR/$nodem" | cut -d\# -f2-
}

function cleanup() {

        find "$CCC_PXEDIR" -name "??-??-??-??-??-??-??" | while read c
        do
          /bin/rm -rf "$c"
        done

	# remove all node data (is going to be rebuild)
        find "$CCC_PXEDIR" -name "??-??-??-??-??-??-??.data" | while read c
        do
          /bin/rm -rf "$c"
        done

        # disable nodes that are not in the current server subnet or has invalid data
        find "$CCC_NODESDIR" -name "??-??-??-??-??-??" | while read c
        do
          node_macaddr=${c##*/}
          if { echo "$node_macaddr" | grep -P '^([0-9a-f]{2}-){5}[0-9a-f]{2}$' &>/dev/null; }
          then
		if test -e "$c" && test -e "$c.disabled"
		then
			/bin/rm -f "$c.disabled"
		fi

		validation=$($0 "$node_macaddr" -v 2>&1)
                if test $? -ne 0
		then
			/bin/mv "$c" "$c.disabled" && echo "$node_macaddr: disabled: $validation";
		else
			$0 "$node_macaddr" -F
		fi
          fi
        done

        # clean all tmp files
        /bin/rm -rf "$CCC_NODESDIR"/.ccc.tmp.* "$CCC_PXEDIR"/.ccc.tmp.* "$CCC_PXEDIR"/.ccc.tmp.* /tmp/.ccc.tmp.* "${CCC_CLUSTERDIR%/}".tmp.*

	# signal external process
        touch "$CCC_DIR/reconfigure"
}

function list() {
 cd "$CCC_NODESDIR" && find . -name "??-??-??-??-??-??" | while read m
 do
  node_macaddr="${m#./}"
  output=$(showdata "$node_macaddr")
  echo -n "$node_macaddr $(echo "$output"|grep ^node_ipdata| cut -d= -f2)"
  echo -n " $(echo "$output"|grep ^node_hostname| cut -d= -f2)"
  echo -n " $(echo "$output"|grep ^node_coreosversion| cut -d= -f2)"
  if test -n "$(echo "$output"|grep '^node_autologin=true')"
  then
          echo -n " autologin"
  else
          echo -n " no-autologin"
  fi
  if test -n "$(echo "$output"|grep '^node_usedisk=true')"
  then
          echo -n " usedisk"
  else
          echo -n " no-usedisk"
  fi
  cloudinit_sum="$(echo "$output"|grep '^node_cloudinit_checksum' | cut -d= -f2 | cut -c1-6)"
  if test -n "$cloudinit_sum"
  then
          echo -n " cloudinit-$cloudinit_sum"
  else
          echo -n " no-cloudinit"
  fi
  echo -n " $(echo "$output"|grep ^node_cluster| cut -d= -f2)"
  echo
 done
}

function recluster() {
 tmpclusterdir="${CCC_CLUSTERDIR%/}.tmp.$(uuid)"
 mkdir -p "$tmpclusterdir"

 cd "$CCC_NODESDIR" && find . -name "??-??-??-??-??-??" | while read m
 do
  node_macaddr="${m#./}"
  output=$(showdata "$node_macaddr")
  node_ipdata="$(echo "$output"|grep ^node_ipdata| cut -d= -f2)"
  node_ip="${node_ipdata%/*}"
  node_hostname="$(echo "$output"|grep ^node_hostname| cut -d= -f2)"
  node_cluster="$(echo "$output"|grep ^node_cluster| cut -d= -f2)"
  if test -n "$node_cluster" && test "-" != "$node_cluster"
  then
   echo "$node_cluster.$CCC_CLUSTERDOMAIN: including node $node_ip ($node_hostname)"
   echo "srv-host=_etcd-server._tcp.$node_cluster.$CCC_CLUSTERDOMAIN,$node_ip,2380,0,0" >> "$tmpclusterdir/$node_cluster"
  fi
 done

 rm -rf "${CCC_CLUSTERDIR%/}"/
 mv "$tmpclusterdir" "${CCC_CLUSTERDIR%/}/"
 touch "$CCC_DIR/reconfigure"
}

case "$1" in
-N) cleanup; exit $? ;;
-R) recluster; exit $? ;;
-L) list; exit $? ;;
??-??-??-??-??-??) ;;
-H|*) echo "$USAGE" 1>&2; exit 2 ;;
esac

if test $# -eq 0
then
	list
	exit $?
fi

export node_macaddr=$1
export converted_mac="$(convert_mac "$node_macaddr")"
export node_mac="$converted_mac"

if test -z "$node_macaddr"
then
	echo "node mac address not specified" 1>&2
	exit 2 
fi

if ! { echo "$node_macaddr" | grep -P '^([0-9a-f]{2}-){5}[0-9a-f]{2}$'; } &>/dev/null
then
        echo "node mac address is invalid or has an incorrect syntax: $node_macaddr" 1>&2
        exit 2
fi
	
test -e "$CCC_NODESDIR/$node_macaddr"
node_is_registered=$?    # 0: registered, 1: not registered

# if no option provided then just check if node is registered and exit with proper code
if test $# -eq 1 && test -n "$node_deregister"
then
	exit $node_is_registered
fi

# defaults
export node_hostname=coreos-$node_macaddr
export node_coreosversion=stable:current
export node_autologin=false
export node_usedisk=false
export node_cluster=-
export node_dns="$CCC_NODES_DNS"
export node_gateway="$CCC_NODES_GATEWAY"
export cluster_domain="$CCC_CLUSTERDOMAIN"


# if node exists load its current data to override defaults
if test $node_is_registered -eq 0
then
	tmp_file="/tmp/.ccc.tmp.$node_macaddr.$(uuid)"
	showdata >"$tmp_file" && source "$tmp_file"
	/bin/rm -f "$tmp_file"
fi

# to start processing options
shift

# now set the new data passed as arguments
while getopts "i:h:c:d:a:l:nevVsfFroOT" OPTION
do
	case $OPTION in
	     i) node_ipdata="$OPTARG" ;;
	     h) node_hostname="$OPTARG" ;;
	     c) node_coreosversion="$OPTARG" ;;
	     d) node_usedisk="$OPTARG" ;;
	     a) node_autologin="$OPTARG" ;;
	     l) node_cluster="$OPTARG" ;;
	     n) node_register=1 ;;
	     e) node_deregister=1 ;;
	     v) node_validate=1 ;;
	     V) node_validate=2 ;;
	     s) node_showdata=1 ;;
	     f) node_reconfigure=1 ;;
	     F) node_reconfigure=2 ;;
	     r) node_remotecmd=1 ;;
	     o) node_cloudinit=1 ;;
	     O) node_cloudinit_out=1 ;;
	     T) node_cloudinit_out=2 ;;
	     *) echo "$USAGE" 1>&2; exit 2 ;;
	esac
done

# if there is a deregistration request
if test -n "$node_deregister"
then
	# if its not the only option then exit
	test $# -eq 1 || { echo "$USAGE" 1>&2; exit 2; }

	{ test $node_is_registered -eq 0 && ! test -e "$CCC_NODESDIR/$node_macaddr.disabled"; } || { echo "node is not registered but cleanup will continue" 1>&2; }
	/bin/rm -rf "$CCC_NODESDIR/$node_macaddr" "$CCC_NODESDIR/$node_macaddr.disabled"
	/bin/rm -rf "$CCC_PXEDIR/"??"-$node_macaddr" "$CCC_PXEDIR/"??"-$node_macaddr".data 
	test -e "$CCC_PXEDIR/"??"-$node_macaddr" && { echo "failed to properly deregister node: $node_macaddr" 1>&2; exit 11; }
	test -e "$CCC_NODESDIR/$node_macaddr" && { echo "failed to deregister node: $node_macaddr" 1>&2; exit 1; }
	
	touch "$CCC_DIR/reconfigure"

	exit $?
fi

# if there is a cloud-config.yml in/out request and no the only option
if { test -n "$node_cloudinit" || test -n "$node_cloudinit_out"; } && test $# -ne 1
then
	echo "$USAGE" 1>&2
	exit 2
fi

# check required non defaults:

# if registering node then ip/prefix is required
if test -n "$node_register" && test -z "$node_ipdata"
then
	echo "node ip/prefix not specified" 1>&2
	exit 2
fi

# if not registering then node must exist
if test -z "$node_register" && test "$node_is_registered" -ne 0
then
	echo "node is not registered: $node_macaddr" 1>&2
	exit 2
fi

# if registering then node must not exist
if test -n "$node_register" && test "$node_is_registered" -ne 1
then
	echo "node is already registered (remove '-n' option to update): $node_macaddr" 1>&2
	exit 2
fi

export node_ipdata
export node_ip=${node_ipdata%/*}
export node_ipprefix=${node_ipdata##*/}
export node_channel=${node_coreosversion%:*}
export node_version=${node_coreosversion##*:}

# if remote execution request then everything after the option is the command
if test -n "$node_remotecmd"
then
	shift 
	
	# if no command passed as arg then read from stdin
	if test $# -eq 0
	then

	  tmpscript=".ccc.tmp.cmd.$(uuid)"

	  sshopts="-i $CCC_SERVERKEYFILE -o StrictHostKeyChecking=no core@$node_ip"

	  { ssh $sshopts cat\>"$tmpscript" && \
	    ssh $sshopts chmod +x "./$tmpscript" && \
	    ssh $sshopts "./$tmpscript"; } || { echo "failed execution of remote command";  exit 1; }

	  ssh $sshopts /bin/rm -rf "./$tmpscript" || { echo "failed to remove temporary remote file: $tmpscript";  exit 1; }

	  exit $?

	else # use the command specified

          ssh -t -i "$CCC_SERVERKEYFILE" -o 'StrictHostKeyChecking=no' core@$node_ip "$@"

	  exit $?

	fi
	
	exit 0
fi

if test "$node_version" = "current" || test -z "$node_version" || test "$node_version" = "$node_channel"
then
	node_version="$(find_latest $node_channel)"
fi
 
function validate_node_data() 
{

  if ! { echo "$node_ip/$node_ipprefix" | grep -P '^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$' &>/dev/null; }
  then
        echo "bad node ip/prefix: $node_ipdata" 1>&2
        return 1
  else
        # check is valid and is on server subnet
        ipcalc -c "$node_ip/$node_ipprefix" || return 1

        if test "$(ipcalc -n $node_ip/$node_ipprefix)" != "NETWORK=$CCC_SERVERSUBNET" || \
           test "$(ipcalc -m $node_ip/$node_ipprefix)" != "NETMASK=$CCC_SERVERNETMASK" || \
           test "$(ipcalc -b $node_ip/$node_ipprefix)" != "BROADCAST=$CCC_SERVERBCAST"
        then
                echo "node ip/prefix does not matches server configured network: $node_ip/$node_ipprefix vs server: $CCC_SERVERIPDATA" 1>&2
                return 1
        fi
  fi

  if ! { echo "$node_hostname" | grep -P '^[a-zA-Z]+[\w-]*[a-zA-Z0-9]+$' &>/dev/null; }
  then
        echo "bad node hostname: $node_hostname" 1>&2
        return 1
  fi

  if ! { echo "$node_channel" | grep -P '^(stable)|(beta)|(alpha)$' &>/dev/null; }
  then
        echo "bad node channel: $node_channel" 1>&2
        return 1
  fi

  if ! { echo "$node_version" | grep -P '^(\d{3,4}\.\d{1,2}\.\d{1,2})$' &>/dev/null; }
  then
        echo "bad node version: $node_version" 1>&2
        return 1
  fi

  if ! test -e "$CCC_CACHEDIR/$node_channel/$node_version/$CCC_COREOS_PXE_VMLINUZ"
  then
	echo "non existing vmlinuz image for: $node_channel:$node_version" 1>&2
	return 1
  fi

  if ! test -e "$CCC_CACHEDIR/$node_channel/$node_version/$CCC_COREOS_PXE_IMAGE_CPIO"
  then
	echo "non existing cpio initrd for: $node_channel:$node_version" 1>&2
	return 1
  fi

  if ! { echo "$node_autologin" | grep -P '^(true|false)$' &>/dev/null; }
  then
        echo "bad node autologin value (use 'true' or 'false'): $node_autologin" 1>&2
        return 1
  fi

  if ! { echo "$node_usedisk" | grep -P '^(true|false)$' &>/dev/null; }
  then
        echo "bad node usedisk value (use 'true' or 'false'): $node_usedisk" 1>&2
        return 1
  fi

  if test "-" != "$node_cluster" && ! { echo "$node_cluster" | grep -P '^[a-z][\w-]+[a-z0-9]$' &>/dev/null; }
  then
        echo "bad node cluster name (use a lowercase name with 3 or more chars, or a single dash to isolate): $node_cluster" 1>&2
        return 1
  fi

  test "$node_validate" = "2" && echo "$node_macaddr"

  return 0
}

function translated_file() {
  origfile=$1
  if ! test -s "$origfile"
  then
	origfile="$CCC_CLOUDINIT_TEMPLATE"
  fi

  if test -e "$origfile"
  then
        cat "$origfile" | sed 's/^/#LN#/' | sed 's/"/\"/g' | while read x; do eval "echo  \"${x#\#LN\#}\" | sed 's/\#LN\#//g'"; done
  fi
}

function needs_oem_rebuild() {

  previous_oem_sum=$(test -e "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/oem.md5sum" && head -1 "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/oem.md5sum" | awk '{ print $1 }')
  current_oem_sum=$(translated_file "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml" | cat - "$CCC_PXEDIR/../amd64-usr/$node_channel/$node_version/coreos_production_pxe_image.cpio.gz" $(find "$CCC_OEMDIR" -type f) | md5sum | cut -d\  -f1)
 
  #echo "current=$current_oem_sum        prev=$previous_oem_sum" 
  test "$current_oem_sum" != "$previous_oem_sum"
  return $?
}

function node_reconfigure() {
    
  tmp_file="$CCC_PXEDIR/.ccc.tmp.$CCC_ARPTYPE-$node_macaddr.$(uuid)"
  
  needs_oem_rebuild

  if test $? -eq 0 || test "2" = "$node_reconfigure"
  then

    echo "$node_macaddr: reconfiguring, rebuilding oem data" 1>&2

    mkdir -p "$tmp_file"
  
    if cd "$tmp_file"
    then
	mkdir -p ./usr/share/oem
	find "$CCC_OEMDIR" -type f | while read f
	do
	 bf=""
	 nf="${f#$CCC_OEMDIR}"
	 nf="${nf#/}"
	 test "$nf" != "${nf%/*}" && bf="${nf%/*}"
	 bf="${bf#/}"
	 #echo "f=$f  nf=$f  bf=$bf"
	 mkdir -p "./usr/share/oem/$bf"
	 cp -r "$f" "./usr/share/oem/$nf"
	 chmod ugo+r ./usr/share/oem/"$nf"
	 test "$nf" != "${nf%.sh}" && chmod ugo+x ./usr/share/oem/"$nf"
        done
	translated_file "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml" >"./usr/share/oem/cloud-config.yml" && \
	gunzip -c "$CCC_PXEDIR/../amd64-usr/$node_channel/$node_version/coreos_production_pxe_image.cpio.gz" >coreos_production_pxe_image.cpio && \
	{ find usr | cpio -o -A -H newc -O coreos_production_pxe_image.cpio 2>/dev/null; } && \
	gzip coreos_production_pxe_image.cpio && \
	mkdir -p "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/" && \
	mv coreos_production_pxe_image.cpio.gz "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/" && \
        echo -n "$current_oem_sum" > "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/oem.md5sum"

	test $? -eq 0 ||  { echo "failed to create oem initrd" 1>&2; rm -rf "$tmp_file"; return 1; }
    fi

    /bin/rm -rf "$tmp_file"

  else
  	echo "$node_macaddr: reconfiguring" 1>&2
  fi

cat>"$tmp_file"<<EEOOFF
default amd64-usr/$node_channel/$node_version/coreos_production_pxe.vmlinuz
append initrd=$(if test -e "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/coreos_production_pxe_image.cpio.gz"; then echo "pxelinux.cfg/$CCC_ARPTYPE-$node_macaddr.data"; else echo "amd64-usr/$node_channel/$node_version"; fi)/coreos_production_pxe_image.cpio.gz $(test "true" = "$node_autologin" && echo "coreos.autologin") $(test "true" = "$node_usedisk" && echo "root=LABEL=CCCROOT") sshkey="$CCC_SERVERKEY"
EEOOFF

  test $? -eq 0 || { echo "failed to create '$tmp_file'" 1>&2; rm -f "$tmp_file"; return 1; }

  if ! cmp "$tmp_file" "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr" &>/dev/null
  then
   /bin/mv "$tmp_file" "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr"
   test $? -eq 0 || { echo "failed to create '$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr'" 1>&2; rm -f "$tmp_file" return 1; }
  fi

  /bin/rm -f "$tmp_file"
  
  touch "$CCC_DIR/reconfigure"

  return $?
}

if test -n "$node_cloudinit"
then
        test $node_is_registered -eq 0 || { echo "node is not registered" 1>&2; exit 11; }

        mkdir -p "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data"
        cat > "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml"

	test -s "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml" || \
		/bin/rm -f "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml"
fi

if test -n "$node_cloudinit_out"
then
        test $node_is_registered -eq 0 || { echo "node is not registered" 1>&2; exit 11; }

	if test "2" = "$node_cloudinit_out"
	then
		translated_file "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml"
	elif test -s "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml"
	then
		cat "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml"
	else
		cat "$CCC_CLOUDINIT_TEMPLATE"
	fi

	exit $?
fi

if test -n "$node_validate" && test $# -eq 1
then
	validate_node_data
	exit $?
fi

if test -z "$node_showdata" || test $# -ne 1
then

tmp_nodefile="$CCC_NODESDIR/.ccc.tmp.$(uuid).${node_macaddr}"

if test -e "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml"
then
	node_cloudinit_checksum=$(md5sum "$CCC_PXEDIR/$CCC_ARPTYPE-$node_macaddr.data/cloud-config.yml" | cut -d\  -f1)
else
	node_cloudinit_checksum=$(md5sum "$CCC_CLOUDINIT_TEMPLATE" | cut -d\  -f1)
fi

cat>"$tmp_nodefile"<<EEOOFF
dhcp-host=$converted_mac,$node_hostname,$node_ip,infinite
#node_ipdata=$node_ipdata
#node_hostname=$node_hostname
#node_coreosversion=$node_channel:$node_version
#node_autologin=$node_autologin
#node_usedisk=$node_usedisk
#node_cluster=$node_cluster
#node_cloudinit_checksum=$node_cloudinit_checksum
EEOOFF

test $? -eq 0 || { echo "failed to create '$tmp_nodefile' while registering node data" 1>&2; exit 11; }

needs_oem_rebuild

# if differs or not currently registered then mv
if test $? -eq 0 || ! cmp "$tmp_nodefile" "$CCC_NODESDIR/$node_macaddr" &>/dev/null
then
	validate_node_data || { /bin/rm "$tmp_nodefile"; exit 11; }
	{ /bin/mv "$tmp_nodefile" "$CCC_NODESDIR/$node_macaddr" && \
	  node_reconfigure "$node_macaddr"; } || { echo "failed to reconfigure node" 1>&2; exit 20; }

elif test $node_is_registered -eq 0 && test -n "$node_reconfigure"
then
	{ validate_node_data && \
  	  node_reconfigure "$node_macaddr"; } || { echo "failed to reconfigure node" 1>&2; exit 20; }
elif test -n "$node_validate"
then
	validate_node_data || exit 1
fi

/bin/rm -rf "$tmp_nodefile"

fi

if test -n "$node_showdata"
then
	showdata
fi
